# Generated by Django 6.0 on 2025-12-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbExtra',
            fields=[
                ('bb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bboard.bb', verbose_name='Объявление')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Требует ремонта?')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительные параметры',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
    ]
