# Generated by Django 6.0 on 2025-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bbextra_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bboard.tag', verbose_name='Тэги'),
        ),
    ]
