# Generated by Django 6.0 on 2025-12-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_bb_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
