# Generated by Django 6.0 on 2025-12-14 09:38

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(validators=[bboard.models.validate_non_negative], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, validators=[bboard.models.validate_title, bboard.models.validate_capital_start], verbose_name='Товар'),
        ),
    ]
